client_config_backend: file
client_config:
  client_id: 866785127210-1abkr0b0i2tavm1s48jbnlfpq8qqambd.apps.googleusercontent.com
  client_secret: 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

# save_credentials: True
# save_credentials_backend: file
# save_credentials_file: credentials.json
# get_refresh_token: False

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install